//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int IdBooking { get; set; }
        public int IdSession { get; set; }
        public int IdUser { get; set; }
        public int IdSeat { get; set; }
        public string Status_book { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
        public virtual User_cinema User_cinema { get; set; }
    }
}
