//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _CinemaBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int IdFilm { get; set; }
        public string Title { get; set; }
        public string Description_film { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Genre { get; set; }
        [Range(0, 10, ErrorMessage = "–ейтинг маЇ бути в≥д 0 до 10.")]
        public Nullable<decimal> Rating { get; set; }
        public int IdAdmin { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
